import type { IssueEmail } from "../types";

// ===== Numéro #5 — version email (charte CryptoLuciole) =====
// Même squelette que issue-01/02/03/04 : on ne reconstruit pas la structure, on remplit.
// Le lien de désinscription est le placeholder %UNSUBSCRIBE_URL% (voir latest.ts).
// Ce numéro : 3 actus, pas de rubrique « À toi de jouer » (décision du 10/09, numéro déjà dense).
export const issue05: IssueEmail = {
  number: 5,
  subject: "CryptoLuciole #5 — Emprunter contre ses cryptos",
  html: `<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CryptoLuciole #5</title>
<!--[if mso]><style>*{font-family:Arial,sans-serif!important;}</style><![endif]-->
</head>
<body style="margin:0; padding:0; background-color:#EEF2F2; -webkit-text-size-adjust:100%;">
<div style="display:none; max-height:0; overflow:hidden; opacity:0; color:#EEF2F2; font-size:1px;">
Le CDP expliqué simplement, Strategy vend bas et rachète haut, le pétrole pousse la Fed vers une hausse des taux, Hyperliquid frappe à la porte des États-Unis, et le protocole où c'est toi qui fixes ton taux d'emprunt.
</div>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#EEF2F2;">
<tr><td align="center" style="padding:24px 12px;">

<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:600px; max-width:600px; background-color:#ffffff; border-radius:16px; overflow:hidden; font-family:'Inter',Helvetica,Arial,sans-serif;">

  <!-- ============ BANDEAU pleine largeur ============ -->
  <tr>
    <td style="padding:0; font-size:0; line-height:0;">
      <img src="https://raw.githubusercontent.com/AntoineBatou/cryptoluciole/main/assets/banniere.png" width="600" alt="CryptoLuciole — La crypto et la DeFi, expliquées en moins de 10 minutes" style="display:block; width:100%; max-width:600px; height:auto; border:0;">
    </td>
  </tr>

  <!-- ============ TITRE DU NUMÉRO ============ -->
  <tr>
    <td style="padding:26px 36px 0 36px;">
      <p style="margin:0; font-size:12px; font-weight:600; color:#94a3b8; letter-spacing:0.6px;">#5 · JEUDI 10 SEPTEMBRE 2026</p>
      <h1 style="margin:6px 0 0 0; font-size:26px; font-weight:800; color:#1A2332; line-height:1.25;">Emprunter contre ses cryptos</h1>
    </td>
  </tr>

  <!-- ============ INTRO ============ -->
  <tr>
    <td style="padding:20px 36px 10px 36px; color:#1A2332;">
      <p style="margin:0 0 16px 0; font-size:16px; line-height:1.65;">Bonjour à toi 👋,</p>
      <p style="margin:0 0 14px 0; font-size:16px; line-height:1.65;">
        Cet été, Strategy a eu besoin de liquidités. Elle a vendu du bitcoin autour de <strong>60 200 $</strong> — et l'a racheté sept semaines plus tard à <strong>80 320 $</strong>.
      </p>
      <p style="margin:0 0 18px 0; font-size:16px; line-height:1.65;">
        Il existe une autre façon de faire, et c'est le sujet du jour : garder ses cryptos et emprunter contre elles. On regarde comment ça marche, ce que ça coûte, et où ça peut mal tourner.
      </p>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f7fafa; border-radius:12px;">
        <tr><td style="padding:18px 22px; font-size:15px; line-height:2; color:#475569;">
          <strong style="color:#1A2332;">Au menu :</strong><br>
          🔦 <strong>On éclaire</strong> — le CDP, emprunter contre ses cryptos<br>
          ✨ <strong>Dans le faisceau</strong> — Strategy vend bas et rachète haut · le pétrole pousse la Fed · Hyperliquid vise les États-Unis<br>
          🔍 <strong>Sous la loupe</strong> — Liquity V2, le protocole où tu fixes ton taux<br>
          📊 <strong>Les repères</strong> — semaine rouge sur toute la ligne<br>
          💡 <strong>Ça brille</strong> — 480 M$ de frais en dix semaines
        </td></tr>
      </table>
    </td>
  </tr>

  <!-- ============ 1. NOTION ============ -->
  <tr><td style="padding:28px 36px 0 36px;">
    <table role="presentation" cellpadding="0" cellspacing="0"><tr><td style="background-color:#e8f7f3; border-radius:30px; padding:6px 16px; font-size:12px; font-weight:700; color:#1d8870; letter-spacing:1.2px;">🔦 ON ÉCLAIRE</td></tr></table>
    <p style="margin:14px 0 16px 0; font-size:22px; font-weight:800; color:#1A2332;">Le CDP : emprunter contre ses cryptos au lieu de les vendre</p>
  </td></tr>
  <tr><td style="padding:0 36px; color:#1A2332;">
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Au <a href="https://www.cryptoluciole.com/numeros/4" style="color:#28B092; font-weight:600; text-decoration:none;">#4</a>, on expliquait comment parier sur le prix du bitcoin sans jamais le détenir. Cette semaine, l'inverse : comment te servir des cryptos que tu détiens comme garantie pour emprunter.</p>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Le principe</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Tu bloques des cryptos que tu possèdes pour obtenir un prêt. Le protocole garde tes bitcoins ou tes ethers, et te prête en échange des <a href="https://www.cryptoluciole.com/glossaire/stablecoin" style="color:#28B092; font-weight:600; text-decoration:none;">stablecoins</a>, que tu peux dépenser librement. Il est certain d'être remboursé pour une raison simple : <strong>il te prête toujours moins, en valeur, que ce que tu as déposé.</strong> Le jour où tu rembourses, tu récupères ton dépôt.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/cdp" style="color:#28B092; font-weight:700; text-decoration:none;">CDP <em>(collateralized debt position)</em></a> — une position de dette garantie par un dépôt. Ton dépôt n'est pas prêté à quelqu'un d'autre : il reste à toi, simplement immobilisé jusqu'au remboursement.</td></tr></table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">L'équivalent existe depuis longtemps en banque privée française : le <strong>crédit lombard</strong>. Tu nantis ton portefeuille de titres auprès de ta banque, elle te consent une ligne de liquidités, et tu n'as rien vendu. Même logique — et, comme en banque, l'établissement peut vendre les titres si leur valeur passe sous un seuil.</p>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Comment ça marche, étape par étape</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Pour suivre les opérations, prenons un exemple pratique : <strong>tu déposes 100 $ de bitcoin sur un protocole de CDP.</strong></p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Tu déposes ta crypto.</strong> Elle devient ta garantie, on appelle cela ton <em>collatéral</em>.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/collateral" style="color:#28B092; font-weight:700; text-decoration:none;">Collatéral</a> — l'actif que tu bloques en garantie de ton emprunt. Tu ne peux plus y toucher tant que la dette n'est pas remboursée.</td></tr></table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Tu choisis combien tu empruntes.</strong> Le rapport entre ce que tu empruntes et ce que tu as déposé s'appelle le <strong>LTV</strong> (<em>loan-to-value</em>). Chaque protocole fixe un plafond, le <strong>LLTV</strong> : le LTV maximum au-delà duquel ta position est liquidée.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/ltv" style="color:#28B092; font-weight:700; text-decoration:none;">LTV <em>(loan-to-value)</em></a> — ta dette rapportée à la valeur de ta garantie. Emprunter 60 $ contre 100 $ de dépôt, c'est un LTV de 60 % (60 ÷ 100). Le <strong>LLTV</strong> est le plafond à ne pas franchir, fixé par le protocole : souvent de l'ordre de 80 % pour un actif liquide comme le bitcoin ou l'ether.</td></tr></table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Avec un plafond à 80 %, tu peux donc emprunter <strong>jusqu'à 80 $</strong> (100 × 0,80). Admettons que tu n'en empruntes que <strong>60 $</strong>, par sécurité.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Le protocole émet les 60 $ de stablecoins.</strong> Il ne pioche pas dans une réserve existante : il crée les jetons à cet instant, adossés à ton dépôt. C'est ce qu'on appelle le <em>mint</em>.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/mint" style="color:#28B092; font-weight:700; text-decoration:none;">Mint</a> — la création de nouveaux jetons par un protocole, à la demande. À l'inverse, quand tu rembourses, les jetons sont détruits (<em>burn</em>) : ils cessent d'exister.</td></tr></table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Ton collatéral peut baisser.</strong> Ta dette, elle, reste figée à 60 $ : elle est libellée en dollars. Le <strong>seuil de liquidation</strong>, c'est le prix auquel ton collatéral devient trop faible pour tenir le plafond.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/liquidation" style="color:#28B092; font-weight:700; text-decoration:none;">Liquidation</a> — la vente forcée de ta garantie par le protocole, automatiquement et sans préavis, dès que ton LTV dépasse le plafond. Sur un CDP, tu ne perds pas ton dépôt : une fois la dette remboursée et la pénalité prélevée, <strong>ce qui reste te revient</strong>.</td></tr></table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Ici, tu es liquidé si ton bitcoin tombe à <strong>75 $</strong> — parce qu'à ce moment-là, ta dette de 60 $ atteint 80 % de ton collatéral (60 ÷ 75 = 0,80). Soit une <strong>baisse de 25 %</strong> par rapport à ton dépôt de départ.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Ce jour-là, trois choses se passent :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>le protocole vend ton collatéral.</strong> Selon les protocoles, il en vend une partie seulement ou la totalité, de quoi rembourser les 60 $ de dette ;</li><li style="margin-bottom:6px;"><strong>il prélève une pénalité</strong>, de l'ordre de <strong>5 à 10 %</strong> de la dette selon les protocoles, soit 3 à 6 $ ici ;</li><li><strong>le reste te revient</strong> : une dizaine de dollars de bitcoin, auxquels s'ajoutent les 60 $ empruntés qui restent à toi — soit <strong>environ 70 $</strong> là où ton bitcoin en valait 75.</li></ul>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le vrai coût n'est pas la pénalité : c'est que la vente a eu lieu au plus bas, et que tu ne profiteras pas du rebond.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Tu paies un intérêt</strong> sur le montant emprunté, tant que la position est ouverte. Sur la quasi-totalité des CDP, ce taux t'est <strong>imposé</strong> — voté par une DAO ou calculé par une formule selon la demande. Liquity fait exception, on y revient plus bas.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">D'un protocole à l'autre, l'écart est énorme : du quasi-gratuit à <strong>plus de 10 % par an</strong>. Et en ce moment, c'est cher presque partout, pour une raison simple : <strong>personne ne prête un dollar en DeFi moins cher que ce que rapporte un dollar placé sans risque.</strong> Tant que les taux américains restent hauts, ils tirent tout le reste vers le haut — un emprunt ouvert au printemps dernier ne coûtait pas ce qu'il coûte aujourd'hui.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Tu rembourses quand tu veux.</strong> Tu rends les 60 $ de stablecoins <strong>plus les intérêts courus</strong>, le protocole détruit les jetons, et <strong>tu récupères tes 100 $ de bitcoin</strong> — quelle que soit leur valeur du jour. Ton bitcoin, lui, n'a pas bougé : ce que l'opération t'a coûté, c'est l'intérêt.</p>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">À quoi ça sert : trois usages</p>
    <p style="margin:16px 0 8px 0; font-size:17px; font-weight:700; color:#1A2332;">1. Dépenser sans vendre</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Tu as besoin de liquidités — mais tu crois à ton bitcoin sur le long terme. Vendre, c'est renoncer à la hausse qui suivra.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Ton bitcoin vaut 100. Tu empruntes 60 et tu les dépenses.</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>Demain, il vaut 200.</strong> Tu vends juste de quoi rembourser les 60. <strong>Il te reste 140.</strong></li><li><strong>Si tu avais vendu 60 de bitcoin au départ</strong>, il ne t'en serait resté que 40 — qui vaudraient 80 aujourd'hui.</li></ul>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>140 contre 80.</strong> (On laisse de côté l'intérêt payé entre-temps, qui ne change pas l'ordre de grandeur.)</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Cette position porte un nom : tu es <strong>long</strong>, ou haussier.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/long" style="color:#28B092; font-weight:700; text-decoration:none;">Long (haussier)</a> — être positionné pour gagner si le prix monte. Emprunter du stablecoin contre du bitcoin, c'est parier que ton collatéral va monter <strong>face au dollar</strong> : ta dette, elle, reste figée en dollars, donc la hausse de l'actif suffit à la solder.</td></tr></table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">C'est tout le sens de l'opération — et son revers est chiffré plus haut : si ton bitcoin tombe à 75, ta position est liquidée, et tu ne verras jamais les 200.</p>
    <p style="margin:16px 0 8px 0; font-size:17px; font-weight:700; color:#1A2332;">2. Prendre du levier</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le stablecoin emprunté sert à racheter de la crypto, qu'on redépose en garantie. C'est du <em>levier</em>, obtenu autrement.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/levier" style="color:#28B092; font-weight:700; text-decoration:none;">Levier</a> — s'exposer à plus que son capital en empruntant la différence. Avec 100 de capital et 60 empruntés, tu es exposé à 160 : chaque mouvement du bitcoin joue sur 160, pas sur 100.</td></tr></table>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Tu déposes 100, tu empruntes 60, tu rachètes 60 de bitcoin : <strong>te voilà exposé à 160 avec 100 de capital.</strong></p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>Le bitcoin monte de 50 %</strong> : tes 160 deviennent 240, tu dois toujours 60, <strong>il te reste 180</strong> au lieu de 150.</li><li><strong>Le bitcoin baisse de 25 %</strong> : tes 160 tombent à 120, tu dois toujours 60, <strong>il te reste 60</strong> au lieu de 75. Tu n'es pas liquidé pour autant : ta dette de 60 ne pèse que la moitié des 120 qui te restent, parce que ton collatéral est plus gros qu'au départ.</li></ul>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Pourquoi passer par là plutôt que par un <a href="https://www.cryptoluciole.com/glossaire/contrat-perpetuel" style="color:#28B092; font-weight:600; text-decoration:none;">contrat perpétuel</a> sur Hyperliquid, qui donne du levier en trois clics ? Deux raisons :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>le coût est connu d'avance.</strong> Tenir une position à la hausse sur le bitcoin coûte actuellement <strong>10,63 % annualisés</strong> de <a href="https://www.cryptoluciole.com/glossaire/funding-rate" style="color:#28B092; font-weight:600; text-decoration:none;">funding</a> — un taux que personne ne fixe, et qui monte précisément quand tout le marché veut être exposé à la hausse ;</li><li><strong>tu détiens de vrais bitcoins dans ton propre portefeuille</strong>, pas une position ouverte chez un opérateur.</li></ul>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le prix à payer est réel : il faut immobiliser bien plus que ce qu'on emprunte, là où un perp se contente de quelques pour cent de marge.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>f(x) Protocol</strong>, un protocole de levier sur Ethereum, pousse cet argument au bout : levier jusqu'à ×7, sans frais de financement, et il accepte le bitcoin en garantie.</p>
    <p style="margin:16px 0 8px 0; font-size:17px; font-weight:700; color:#1A2332;">3. Emprunter à un taux pour placer à un taux plus élevé</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <strong>Carry trade</strong> — emprunter là où l'argent est bon marché pour le placer là où il rapporte davantage, et encaisser la différence. Le gain ne vient pas d'une hausse de prix, mais de l'écart entre deux taux.</td></tr></table>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Rien de nouveau : la finance traditionnelle le pratique depuis des décennies. Le cas d'école est le carry trade sur le yen :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>on emprunte au Japon</strong>, où l'argent reste beaucoup moins cher qu'ailleurs ;</li><li style="margin-bottom:6px;"><strong>on convertit en dollars</strong> et on achète des obligations d'État américaines, qui rapportent nettement plus ;</li><li><strong>on empoche l'écart</strong> entre les deux taux.</li></ul>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le risque n'est pas dans les taux, il est dans la monnaie : si le yen remonte brutalement, la dette à rembourser gonfle et le gain s'évapore. C'est arrivé plusieurs fois.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;"><strong>En DeFi, le même montage existe : tu empruntes des dollars à un certain taux et tu les places à un taux plus élevé.</strong> Par exemple sur f(x) Protocol :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;">tu déposes des bitcoins et tu empruntes des fxUSD. Coût : <strong>0,5 %</strong> à l'ouverture et <strong>0,2 %</strong> à la fermeture ;</li><li>tu places ces fxUSD là où ils rapportent. Le plus direct, c'est le <strong>pool de stabilité de f(x)</strong> lui-même, qui sert <strong>6,71 %</strong> en ce moment. Tu peux aussi les échanger contre des USDC ou des USDT et viser une autre stratégie : par exemple les coffres USDC de <strong>Morpho</strong> entre <strong>3,19 % et 5,61 %</strong>.</li></ul>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Tu empoches la différence. Par exemple, avec <strong>100 000 $</strong> de bitcoin déposés :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;">tu empruntes <strong>60 000 $</strong> de fxUSD, soit un LTV de 60 % ;</li><li style="margin-bottom:6px;">tu paies 0,5 % à l'ouverture et 0,2 % à la fermeture : <strong>0,7 % de 60 000 = 420 $</strong> ;</li><li style="margin-bottom:6px;">tu les places à 6,71 % : <strong>60 000 × 6,71 % = 4 030 $</strong> de gains sur l'année ;</li><li>une fois les frais déduits, <strong>4 030 − 420 = 3 610 $</strong> — sans avoir vendu un seul bitcoin, et en gardant l'intégralité de la hausse s'il monte.</li></ul>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Ce rendement de 6,71 % n'est pas magique, et il faut savoir d'où il vient : <strong>le pool de stabilité sert à absorber les liquidations</strong>. Quand un emprunteur se fait liquider, c'est l'argent du pool qui rembourse sa dette, et les déposants reçoivent son collatéral avec une décote. Tu es payé pour ce service, et pour le risque qui va avec.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Chaque fois que tu vises un rendement, pose-toi la même question : qui paie, et pour quel risque ?</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Trois réserves, avant de trouver ça trop beau :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>ton bitcoin reste liquidable</strong> si le marché décroche ;</li><li style="margin-bottom:6px;"><strong>le 6,71 % n'est pas garanti</strong> : c'est un rendement variable, qui dépend du nombre de déposants dans le pool et du volume de liquidations à absorber. Il peut tomber bien plus bas du jour au lendemain, et c'est lui qui fait toute la marge de l'opération ;</li><li><strong>f(x) est un petit protocole</strong> : environ <strong>126 M$</strong> déposés, quand Sky ou Morpho comptent en milliards. Moins de recul, moins de liquidité pour entrer et sortir — l'emprunt à 0 % se paie aussi en risque de protocole.</li></ul>
    <p style="margin:0 0 14px 0; font-size:15px; line-height:1.6; color:#64748b; font-style:italic;">On décrit ici une stratégie pour l'expliquer, pas pour la recommander.</p>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Pourquoi ça compte cette semaine</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Strategy avait du bitcoin et besoin de liquidités cet été : elle a vendu du bitcoin pour payer un dividende, et l'a racheté 33 % plus cher deux mois plus tard. On y revient juste après.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le CDP est la réponse que la DeFi apporte à ce problème. Reste qu'il n'aurait pas forcément été applicable ici : emprunter contre du bitcoin suppose en général de le transférer d'abord sur une blockchain capable d'exécuter des contrats, ce qui cadre mal avec la doctrine de conservation de Strategy.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Un peu plus bas, on ouvre le capot de l'un de ces protocoles : <strong>Liquity</strong>.</p>
    <p style="margin:0 0 4px 0; font-size:14px; line-height:1.6; color:#64748b; font-style:italic;">Une dernière chose, souvent évoquée : certains voient dans le CDP un moyen de repousser l'impôt tout en profitant de leurs gains — on ne vend rien, on emprunte, donc on estime pouvoir dépenser ces stablecoins sans déclarer de plus-value. Prudence : on ne sait pas si l'administration fiscale l'entendrait de cette oreille.</p>
  </td></tr>

  <tr><td style="padding:26px 36px 0 36px;"><div style="border-top:1px solid #eef2f2;"></div></td></tr>

  <!-- ============ 2. ACTUS ============ -->
  <tr><td style="padding:24px 36px 0 36px;">
    <table role="presentation" cellpadding="0" cellspacing="0"><tr><td style="background-color:#fff4e0; border-radius:30px; padding:6px 16px; font-size:12px; font-weight:700; color:#b9770f; letter-spacing:1.2px;">✨ DANS LE FAISCEAU</td></tr></table>
  </td></tr>

  <tr><td style="padding:18px 36px 0 36px; color:#1A2332;">
    <p style="margin:0 0 6px 0; font-size:17px; font-weight:700;"><span style="color:#F5A623;">✦</span>&nbsp; Strategy a vendu du bitcoin à 60 200 $, elle en rachète à 80 320 $</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">Fin juin, Strategy — la société de Michael Saylor, croisée au <a href="https://www.cryptoluciole.com/numeros/1" style="color:#28B092; font-weight:600; text-decoration:none;">#1</a> et au <a href="https://www.cryptoluciole.com/numeros/3" style="color:#28B092; font-weight:600; text-decoration:none;">#3</a>, et à qui on a consacré un <a href="https://www.cryptoluciole.com/dossiers/dat" style="color:#28B092; font-weight:600; text-decoration:none;">dossier complet sur les DAT</a> — avait besoin de liquidités pour payer les dividendes de ses titres <strong>STRC</strong>. Elle a vendu du bitcoin en deux fois, <strong>le 30 juin et le 6 juillet</strong>.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <strong>STRC (Digital Credit)</strong> — des titres émis par Strategy qui versent un dividende régulier à leurs porteurs, un peu comme une obligation. C'est de l'argent qui doit sortir chaque trimestre, quoi qu'il arrive, alors que le bitcoin détenu en face, lui, ne rapporte rien tant qu'on ne le vend pas.</td></tr></table>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;"><strong>Sept semaines plus tard, du 24 au 30 août</strong>, elle est revenue à l'achat. Saylor a résumé l'épisode d'un « <em>We're back</em> ».</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #eef2f2; border-radius:12px; overflow:hidden; margin:0 0 15px 0;">
      <tr style="background-color:#1A2332;">
        <td style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8; letter-spacing:0.5px;"></td>
        <td align="right" style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8; letter-spacing:0.5px;">VENDU</td>
        <td align="right" style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8; letter-spacing:0.5px;">RACHETÉ</td>
      </tr>
      <tr><td style="padding:12px 14px; font-size:15px; color:#475569;">Quand</td><td align="right" style="padding:12px 14px; font-size:15px; color:#1A2332;">30 juin et 6 juillet</td><td align="right" style="padding:12px 14px; font-size:15px; color:#1A2332;">24 au 30 août</td></tr>
      <tr style="background-color:#f7fafa;"><td style="padding:12px 14px; font-size:15px; color:#475569;">Combien</td><td align="right" style="padding:12px 14px; font-size:15px; color:#1A2332;">3 588 BTC</td><td align="right" style="padding:12px 14px; font-size:15px; color:#1A2332;">4 603 BTC</td></tr>
      <tr><td style="padding:12px 14px; font-size:15px; color:#475569;">Montant</td><td align="right" style="padding:12px 14px; font-size:15px; color:#1A2332;">~216 M$</td><td align="right" style="padding:12px 14px; font-size:15px; color:#1A2332;">369,7 M$</td></tr>
      <tr style="background-color:#f7fafa;"><td style="padding:12px 14px; font-size:15px; color:#475569;">Prix moyen</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#dc2626;">~60 200 $</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#16a34a;">~80 320 $</td></tr>
    </table>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">L'écart fait <strong>+33 %</strong>, soit <strong>environ 20 100 $ de plus par bitcoin</strong> racheté. Le rachat a été financé par une émission de <strong>4,53 millions d'actions MSTR</strong>.</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;"><strong>Dit simplement : Strategy a vendu bas et racheté haut.</strong> Racheter les 3 588 bitcoins cédés cet été lui a coûté environ <strong>72 M$ de plus</strong> que ce qu'ils lui avaient rapporté — l'équivalent de sept semaines d'attente au mauvais moment.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Deux choses à garder en tête avant d'en tirer une leçon :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>la vente portait sur moins de 0,5 % de la réserve</strong>, qui atteint aujourd'hui <strong>845 050 BTC</strong> — à cette échelle, l'opération ne change rien au bilan de la société ;</li><li><strong>au <a href="https://www.cryptoluciole.com/numeros/3" style="color:#28B092; font-weight:600; text-decoration:none;">#3</a></strong>, on décrivait le <em>Digital Credit Capital Framework</em>, ce cadre par lequel Strategy s'autorise à céder du bitcoin pour honorer ses engagements. Ce n'est donc pas un accident : c'est le dispositif qui a fonctionné comme annoncé.</li></ul>
    <p style="margin:0 0 8px 0; font-size:16px; font-weight:800; color:#28B092;">Le même problème, vu de la DeFi</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Avoir besoin de dollars sans vouloir se séparer de son bitcoin, c'est précisément ce à quoi le <a href="https://www.cryptoluciole.com/glossaire/cdp" style="color:#28B092; font-weight:600; text-decoration:none;">CDP</a> répond. Une société cotée ne peut pas simplement faire ça, et il vaut mieux le dire :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>la comptabilité et l'audit</strong> : une dette contractée auprès d'un contrat automatisé, garantie par des bitcoins immobilisés, est autrement plus difficile à faire valider par des commissaires aux comptes qu'une émission d'actions classique ;</li><li><strong>la liquidation.</strong> Strategy s'est donné un cadre pour céder du bitcoin à la marge, en décidant du moment et du montant. Un collatéral vendu de force par un protocole, un jour de décrochage, lui retirerait exactement cette maîtrise — automatiquement, et sur une blockchain publique.</li></ul>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4; border-left:4px solid #28B092; border-radius:8px; margin-bottom:14px;"><tr><td style="padding:14px 18px; font-size:16px; line-height:1.65; color:#1A2332;">💡 <strong>Notre avis :</strong> on ne juge pas la décision : payer un dividende dû n'est pas facultatif, et 3 588 bitcoins sur 845 050 ne pèsent rien. Ce qui se voit ici, c'est le <strong>coût du calendrier</strong> : moins de deux mois ont suffi à rendre le rachat 33 % plus cher. Et le bitcoin s'échange aujourd'hui autour de <strong>77 300 $</strong>, soit bien sous le prix de ce rachat — et à peine au-dessus du prix de revient moyen de toute la réserve, <strong>75 412 $</strong> selon le dernier dépôt de la société.</td></tr></table>
  </td></tr>

  <tr><td style="padding:18px 36px 0 36px; color:#1A2332;">
    <p style="margin:0 0 6px 0; font-size:17px; font-weight:700;"><span style="color:#F5A623;">✦</span>&nbsp; Le pétrole s'envole, et la Fed pourrait remonter ses taux</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">L'escalade militaire entre les États-Unis et l'Iran a fait repasser le baril de Brent <strong>au-dessus de 100 $</strong> le 9 septembre, en hausse de près de <strong>3 % sur la seule journée</strong>, après que Téhéran a annoncé avoir frappé deux navires américains et huit pétroliers dans le Golfe. Un pétrole cher renchérit le transport, l'énergie et la production : c'est de l'inflation qui arrive dans les mois qui suivent.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Et l'inflation est précisément ce que la banque centrale américaine a pour mandat de contenir. D'où deux échéances rapprochées :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>le 11 septembre</strong>, la publication du <strong>CPI</strong> d'août — l'indice des prix à la consommation, la mesure officielle de l'inflation américaine ;</li><li><strong>le 16 septembre</strong>, la décision de la <strong>Fed</strong> sur une éventuelle hausse de son taux directeur, aujourd'hui à <strong>3,50-3,75 %</strong>.</li></ul>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <a href="https://www.cryptoluciole.com/glossaire/taux-directeur" style="color:#28B092; font-weight:700; text-decoration:none;">Taux directeur</a> — le taux auquel la banque centrale prête aux banques. C'est le prix de départ de l'argent : tout le reste s'en déduit, du crédit immobilier au rendement d'une obligation d'État. Quand il monte, emprunter coûte plus cher partout ; placer « sans risque » rapporte plus.</td></tr></table>
    <p style="margin:0 0 8px 0; font-size:16px; font-weight:800; color:#28B092;">On parle d'une hausse, pas d'une baisse</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">Ça va à rebours de ce que le marché anticipait depuis des mois. Au <strong>9 septembre</strong>, les relevés donnaient entre <strong>56 % et 65 %</strong> de probabilité d'une hausse de 0,25 point le 16. Le CPI du 11 fera pencher la balance.</p>
    <p style="margin:0 0 8px 0; font-size:16px; font-weight:800; color:#28B092;">Ce que ça changerait pour la crypto</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>Placer sans risque rapporte davantage.</strong> Une obligation d'État américaine mieux rémunérée rend moins attractif un actif qui ne verse rien par lui-même, bitcoin compris. On pourrait donc potentiellement voir baisser la valorisation des actifs risqués — actions comme cryptos — mais la relation n'est pas toujours directe. <strong>Attention, rappel :</strong> si tu as réalisé un emprunt sur un CDP et que le prix de ton collatéral baisse, ton LTV remonte tout seul — tu te rapproches donc du seuil de liquidation sans avoir rien fait, juste parce que le marché a bougé.</li><li><strong>À l'inverse, un maintien des taux actuels</strong> retirerait cette pression : quand le prix de l'argent cesse de monter, les actifs risqués respirent. Sans garantie non plus — une partie de ce scénario est déjà dans les prix, puisque le marché lui donne aujourd'hui un peu plus d'une chance sur trois.</li></ul>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4; border-left:4px solid #28B092; border-radius:8px; margin-bottom:14px;"><tr><td style="padding:14px 18px; font-size:16px; line-height:1.65; color:#1A2332;">💡 <strong>Notre avis :</strong> un CPI plus doux que prévu le 11 suffirait à tout renverser : personne ne sait ce que fera la Fed le 16. Ce qui est certain, en revanche, c'est que le prix de l'argent redevient le sujet, en bourse comme en DeFi.<br><br>C'est ce qui donne sa valeur pratique à la notion vue plus haut : <strong>le LTV que tu choisis n'est pas un réglage abstrait, c'est la marge que tu te laisses</strong> le jour où une tension géopolitique fait décrocher ton collatéral de 3 % en quelques jours, comme cette semaine. Une position ouverte au maximum autorisé ne laisse aucune place à ce genre de secousse.</td></tr></table>
  </td></tr>

  <tr><td style="padding:18px 36px 0 36px; color:#1A2332;">
    <p style="margin:0 0 6px 0; font-size:17px; font-weight:700;"><span style="color:#F5A623;">✦</span>&nbsp; Hyperliquid pourrait ouvrir ses marchés aux Américains</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">D'après Bloomberg, <strong>Hyperliquid Labs discute avec Payward</strong>, la maison-mère de Kraken (une plateforme d'échange concurrente de Binance), pour donner accès à ses marchés depuis les États-Unis. Le véhicule serait <strong>Bitnomial</strong>, une filiale de Payward rachetée début 2026, qui dispose déjà des agréments américains de bourse, de compensation et de courtage.</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">Ce qui serait proposé : une sélection de <a href="https://www.cryptoluciole.com/glossaire/contrat-perpetuel" style="color:#28B092; font-weight:600; text-decoration:none;">contrats perpétuels</a> adossés aux marchés d'Hyperliquid, réservés à des utilisateurs américains enregistrés. On avait expliqué ces contrats au <a href="https://www.cryptoluciole.com/numeros/4" style="color:#28B092; font-weight:600; text-decoration:none;">#4</a>.</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">Le dossier est politique autant que technique : le 19 août, <strong>Donald Trump a déclaré que la CFTC travaillait à faire entrer Hyperliquid aux États-Unis « de manière pleinement conforme et légale »</strong> — en nommant Hyperliquid, et elle seule, devant des représentants de Coinbase, Kraken, du Nasdaq et du CME. Le jeton HYPE a bondi dans la foulée.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;">Rien n'est acquis à ce stade :</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;">la structure a été présentée à la <strong>CFTC</strong>, le régulateur américain des marchés dérivés, dont le feu vert est indispensable pour proposer des contrats perpétuels à des résidents américains. L'approbation n'est <strong>pas obtenue</strong> : une ancienne juriste de la SEC estime le processus à <strong>10 à 12 mois</strong> ;</li><li style="margin-bottom:6px;">ni Hyperliquid ni Payward n'ont commenté ;</li><li>les termes financiers ne sont pas connus.</li></ul>
    <p style="margin:0 0 8px 0; font-size:16px; font-weight:800; color:#28B092;">Pourquoi c'est compliqué pour Hyperliquid</p>
    <p style="margin:0 0 15px 0; font-size:16px; line-height:1.7;">Hyperliquid traite <strong>plus de 4 milliards de dollars de volume par jour</strong> sans opérateur central : on s'y connecte avec un portefeuille, sans compte ni vérification d'identité. C'est exactement ce fonctionnement qui l'a tenu hors des États-Unis jusqu'ici — un cadre réglementé suppose quelqu'un d'identifiable pour répondre au régulateur. (Notre fiche complète : <a href="https://www.cryptoluciole.com/protocoles/hyperliquid" style="color:#28B092; font-weight:600; text-decoration:none;">Hyperliquid</a>.)</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4; border-left:4px solid #28B092; border-radius:8px; margin-bottom:14px;"><tr><td style="padding:14px 18px; font-size:16px; line-height:1.65; color:#1A2332;">💡 <strong>Notre avis :</strong><ul style="margin:8px 0 0 0; padding-left:20px;"><li style="margin-bottom:8px;"><strong>Pour Hyperliquid, ce serait une très bonne affaire.</strong> Le modèle qui se dessine n'est pas d'ouvrir son propre site aux Américains, mais de laisser des acteurs agréés brancher leurs clients sur son infrastructure. Elle encaisserait une part des frais sans renoncer à ce qui fait sa force — et ces marchés délégués sont déjà sa <strong>deuxième source de revenus</strong>, derrière ses propres perpétuels.</li><li><strong>Pour l'utilisateur de ces marchés-là, en revanche, les garanties changent.</strong> Pour être conforme, l'opérateur doit pouvoir filtrer les inscrits, fermer une position et déplacer un collatéral. Des fonctions de ce type ont été testées cet été sur le réseau d'essai d'Hyperliquid. Autrement dit : la promesse « personne ne peut toucher à tes fonds » ne vaudrait plus pour qui passe par cette porte.</li></ul></td></tr></table>
  </td></tr>

  <tr><td style="padding:26px 36px 0 36px;"><div style="border-top:1px solid #eef2f2;"></div></td></tr>

  <!-- ============ 3. PROTOCOLE ============ -->
  <tr><td style="padding:24px 36px 0 36px;">
    <table role="presentation" cellpadding="0" cellspacing="0"><tr><td style="background-color:#e8f7f3; border-radius:30px; padding:6px 16px; font-size:12px; font-weight:700; color:#1d8870; letter-spacing:1.2px;">🔍 SOUS LA LOUPE</td></tr></table>
    <p style="margin:14px 0 16px 0; font-size:22px; font-weight:800; color:#1A2332;">Liquity V2 <span style="color:#94a3b8; font-weight:600; font-size:18px;">le CDP où c'est toi qui fixes ton taux</span></p>
  </td></tr>
  <tr><td style="padding:0 36px; color:#1A2332;">
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;"><strong style="color:#28B092;">En bref.</strong> <strong>Liquity V2</strong> est un protocole de <a href="https://www.cryptoluciole.com/glossaire/cdp" style="color:#28B092; font-weight:600; text-decoration:none;">CDP</a> sur Ethereum. Tu y déposes de l'<strong>ether</strong>, du <strong>wstETH</strong> (l'ether staké de Lido) ou du <strong>rETH</strong> (celui de Rocket Pool) — pas de bitcoin — et tu empruntes en échange le stablecoin maison, le <strong>BOLD</strong>.</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>Mise en ligne</strong> : 2021 pour la V1, janvier 2025 pour la V2, dont les contrats actuels ont été redéployés en mai 2025 ;</li><li style="margin-bottom:6px;"><strong>montant déposé sur la V2</strong> : <strong>95,6 M$</strong>, dont un peu plus de la moitié en wstETH ;</li><li style="margin-bottom:6px;"><strong>audité en profondeur</strong> : Trail of Bits, ChainSecurity, Dedaub, Coinspect, Certora (vérification formelle), Recon, plus un concours ouvert de cinq semaines qui a mobilisé plus de 800 chercheurs pour 350 000 $ de primes ;</li><li style="margin-bottom:6px;">contrats <strong>immuables</strong> et <strong>sans gouvernance</strong> ;</li><li><strong>dette minimum : 2 000 BOLD</strong>, soit un ticket d'entrée d'environ 2 000 $ de dette — et donc plus de 2 400 $ de dépôt.</li></ul>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Comment ça marche</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le dépôt, l'emprunt, le seuil de liquidation : tout ce qu'on a vu plus haut s'applique tel quel. Ce qui rend Liquity différent tient en une phrase : <strong>c'est l'emprunteur qui fixe le taux d'intérêt qu'il paiera.</strong></p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Pas de DAO qui vote un taux tous les mois, pas de formule qui le calcule en fonction de la demande. Tu choisis ton chiffre à l'ouverture, <strong>entre 0,5 % et 25 % par an</strong>, et tu peux le modifier quand tu veux ensuite.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">À l'ouverture, le protocole prélève par ailleurs des <strong>frais d'entrée</strong> équivalents à sept jours d'intérêt au taux moyen de ta branche — de l'ordre de <strong>0,1 % du montant emprunté</strong> pour un taux de 5 %, et rien ensuite.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Formulé ainsi, la réponse paraît évidente : tout le monde met 0,5 %. Sauf qu'il y a une contrepartie.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Les redemptions.</strong> N'importe qui, à tout moment, peut apporter 1 BOLD au protocole et repartir avec 1 $ de collatéral. C'est ce qui tient le prix du BOLD collé au dollar : dès qu'il passe sous 1 $, il devient rentable de l'acheter au rabais pour le rendre au protocole contre un dollar d'ether.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f6f6; border-radius:8px; margin:0 0 14px 0;"><tr><td style="padding:12px 16px; font-size:14px; line-height:1.6; color:#475569;">📖 <strong>Redemption</strong> — l'échange de 1 BOLD contre 1 $ de collatéral, ouvert à tous. Concrètement, le protocole prend l'ether d'un emprunteur, le donne à celui qui a apporté le BOLD, et efface d'autant la dette de l'emprunteur.</td></tr></table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Reste à savoir <strong>chez qui</strong> le protocole va prendre cet ether. Et la règle est simple : <strong>on ponctionne d'abord les emprunteurs qui ont fixé le taux le plus bas</strong>, puis on remonte.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le marchandage : payer moins cher, c'est accepter de se faire rembourser d'office avant les autres. Payer plus cher, c'est acheter la tranquillité.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;"><strong>Un exemple.</strong> Deux emprunteurs déposent chacun <strong>100 $</strong> d'ether et empruntent <strong>50 BOLD</strong>.</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>Alix</strong> fixe son taux à <strong>5 %</strong> : elle paie 2,50 $ par an (50 × 0,05) ;</li><li><strong>Bruno</strong> fixe le sien à <strong>9 %</strong> : il paie 4,50 $ par an (50 × 0,09), soit 2 $ de plus qu'Alix.</li></ul>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le BOLD passe brièvement sous 1 $ sur le marché. Un arbitragiste en achète 20 au rabais et les apporte au protocole pour toucher 20 $ d'ether : c'est une redemption, et elle tape <strong>Alix la première</strong>, puisqu'elle paie le taux le plus bas.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Le protocole efface 20 $ de sa dette et prélève 20 $ d'ether sur son dépôt. Elle ne perd pas d'argent au passage. Mais elle n'a plus que <strong>80 $</strong> d'ether exposés à la hausse au lieu de 100, alors que c'était toute la raison de son emprunt. Bruno, lui, n'a rien vu passer : ses 2 $ de plus par an lui ont acheté ça.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Deux choses à en retenir. D'abord, <strong>si aucune redemption n'arrive de l'année, c'est Alix qui a eu raison</strong> : elle a emprunté deux fois moins cher que Bruno pour exactement le même service. Ensuite, elle n'est pas condamnée à subir : <strong>elle peut relever son taux quand elle veut</strong> pour repasser derrière les autres dans la file d'attente.</p>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Ce que ça coûte vraiment d'emprunter</p>
    <p style="margin:0 0 10px 0; font-size:16px; line-height:1.7;">Ce mécanisme donne un résultat mesurable, et c'est le chiffre le plus intéressant du protocole. Voici les taux <strong>réellement payés</strong> aujourd'hui par l'ensemble des emprunteurs de chaque branche :</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #eef2f2; border-radius:12px; overflow:hidden; margin:0 0 14px 0;">
      <tr style="background-color:#1A2332;"><td style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8;">BRANCHE</td><td align="right" style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8;">DETTE TOTALE</td><td align="right" style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8;">TAUX MOYEN PAYÉ</td></tr>
      <tr><td style="padding:12px 14px; font-size:15px; color:#1A2332;">ETH</td><td align="right" style="padding:12px 14px; font-size:15px; color:#475569;">11,2 M BOLD</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#1A2332;">3,21 %</td></tr>
      <tr style="background-color:#f7fafa;"><td style="padding:12px 14px; font-size:15px; color:#1A2332;">wstETH</td><td align="right" style="padding:12px 14px; font-size:15px; color:#475569;">18,9 M BOLD</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#1A2332;">1,09 %</td></tr>
      <tr><td style="padding:12px 14px; font-size:15px; color:#1A2332;">rETH</td><td align="right" style="padding:12px 14px; font-size:15px; color:#475569;">4,2 M BOLD</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#1A2332;">5,77 %</td></tr>
      <tr style="background-color:#f7fafa;"><td style="padding:12px 14px; font-size:15px; font-weight:700; color:#1A2332;">Ensemble</td><td align="right" style="padding:12px 14px; font-size:15px; font-weight:700; color:#1A2332;">34,3 M BOLD</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:800; color:#28B092;">2,36 %</td></tr>
    </table>
        <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Le rendement : l'autre côté du marché</p>
    <p style="margin:0 0 10px 0; font-size:16px; line-height:1.7;">Le protocole permet aussi une stratégie non pas d'emprunt mais de rendement, en faisant fructifier ses BOLD : il suffit de les déposer dans les <strong>pools de stabilité</strong>. Rendements du jour :</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #eef2f2; border-radius:12px; overflow:hidden; margin:0 0 14px 0;">
      <tr style="background-color:#1A2332;"><td style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8;">POOL DE STABILITÉ</td><td align="right" style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8;">RENDEMENT ANNUEL</td></tr>
      <tr><td style="padding:12px 14px; font-size:15px; color:#1A2332;">Branche ETH</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#1A2332;">2,17 %</td></tr>
      <tr style="background-color:#f7fafa;"><td style="padding:12px 14px; font-size:15px; color:#1A2332;">Branche wstETH</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#1A2332;">3,88 %</td></tr>
      <tr><td style="padding:12px 14px; font-size:15px; color:#1A2332;">Branche rETH</td><td align="right" style="padding:12px 14px; font-size:16px; font-weight:700; color:#1A2332;">3,94 %</td></tr>
    </table>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Pas de jeton distribué en récompense, pas d'émission inflationniste : <strong>l'argent que touche le déposant vient entièrement des emprunteurs</strong>, par deux canaux — les intérêts qu'ils paient, et le collatéral récupéré avec une décote quand l'un d'eux se fait liquider. Et aucune société ne prélève sa part au passage : les 100 % repartent vers les utilisateurs.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">En échange, tu rends un service. <strong>Le pool de stabilité absorbe les liquidations</strong> : quand un emprunteur passe sous son seuil, c'est le BOLD du pool qui rembourse sa dette, et les déposants reçoivent son collatéral avec une décote. Tu peux donc ressortir avec un peu moins de BOLD et un peu d'ether en plus — ce qui est un gain tant que l'ether ne s'effondre pas dans la foulée.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Sur un an, ne compte pas sur un chiffre fixe. Sur les douze derniers mois, ces pools ont passé l'essentiel du temps <strong>entre 1 % et 5 %</strong>, avec une médiane de <strong>3 % à 4,3 %</strong> selon la branche.</p>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Les risques &nbsp;<span style="background-color:#fef9c3; color:#a16207; border-radius:20px; padding:3px 12px; font-size:13px; font-weight:700;">🟡 Moyen</span></p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;"><strong>Ce qui rassure.</strong> Personne ne peut changer les règles pendant que ton argent est là, et le code a été passé au crible par six cabinets, dont un en vérification formelle, plus un concours ouvert de cinq semaines.</p>
    <p style="margin:0 0 8px 0; font-size:16px; line-height:1.7;"><strong>Ce qui l'empêche de descendre à « faible ».</strong> Le prix de l'immuabilité est réel — <strong>ce qui ne peut pas être modifié ne peut pas non plus être corrigé</strong> — et ce n'est pas le seul point.</p>
    <ul style="margin:0 0 14px 0; padding-left:20px; font-size:16px; line-height:1.7;"><li style="margin-bottom:6px;"><strong>Un audit ne garantit rien.</strong> Trois semaines après le lancement de janvier 2025, un bug critique a été découvert dans les pools de stabilité malgré tout cet arsenal. Contrats immuables oblige, il n'y avait pas de correctif possible : le protocole a été <strong>entièrement redéployé</strong> et relancé en mai 2025, sans perte de fonds pour les utilisateurs.</li><li style="margin-bottom:6px;"><strong>La <a href="https://www.cryptoluciole.com/glossaire/liquidation" style="color:#28B092; font-weight:600; text-decoration:none;">liquidation</a> est bien réelle.</strong> Le <a href="https://www.cryptoluciole.com/glossaire/ltv" style="color:#28B092; font-weight:600; text-decoration:none;">LTV</a> plafonne à <strong>90,91 % sur la branche ETH</strong>, <strong>83,33 % sur wstETH et rETH</strong>. Emprunter au maximum, c'est se faire liquider au premier décrochage sérieux.</li><li style="margin-bottom:6px;"><strong>La redemption est le risque propre à Liquity.</strong> Fixer un taux bas pour économiser, c'est se placer en tête de file. Une position ouverte et jamais surveillée peut se retrouver largement remboursée d'office — sans perte sèche, mais sans l'exposition qu'on était venu chercher.</li><li style="margin-bottom:6px;"><strong>Tout est adossé à l'ether.</strong> Un décrochage brutal touche les trois branches en même temps, il n'y a pas de diversification du collatéral.</li><li><strong>Le protocole est petit</strong> : <strong>95,6 M$</strong>, loin des poids lourds du secteur. Moins de liquidité sur le BOLD, donc plus de frottement pour entrer et sortir en montant.</li></ul>
    <p style="margin:18px 0 10px 0; font-size:16px; font-weight:800; color:#28B092;">Pourquoi ça compte</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Presque tous les protocoles de prêt te servent un taux calculé par une formule ou voté par une DAO : tu le subis, et il peut doubler du jour au lendemain si la demande d'emprunt s'emballe. Liquity fait l'inverse — il te laisse choisir ton taux, qui ne bouge ensuite que si tu le décides, contre un risque nommé et compréhensible.</p>
    <p style="margin:0 0 14px 0; font-size:16px; line-height:1.7;">Et le résultat n'est pas cosmétique : <strong>2,36 % en moyenne contre 9 à 15 % chez Sky selon le collatéral</strong> — f(x), lui, ne facture aucun intérêt annuel, mais sur un modèle différent (droit d'entrée et de sortie).</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4; border-left:4px solid #28B092; border-radius:8px; margin-bottom:14px;"><tr><td style="padding:14px 18px; font-size:16px; line-height:1.65; color:#1A2332;">💡 <strong>Notre avis :</strong> le design est honnête, et rare : le protocole ne cherche pas à te vendre un rendement, il organise un marché entre ceux qui empruntent et ceux qui prêtent, et il leur reverse tout.<br><br>Côté emprunteur, c'est aujourd'hui l'une des meilleures adresses pour emprunter contre de l'ether.<br><br>Côté déposant, entre <strong>2 % et 4 %</strong> en ce moment, c'est dans le bas de la fourchette des placements en stablecoins. Logique : ce rendement ne vient que des intérêts réellement payés, pas d'un jeton distribué pour attirer les dépôts. C'est moins généreux, et plus solide.<br><br>Reste la limite qui décidera pour beaucoup : <strong>pas de bitcoin en garantie</strong>.</td></tr></table>
    <p style="margin:0 0 4px 0; font-size:11px; line-height:1.5; color:#94a3b8;">Taux moyens réellement payés : lecture directe des contrats <em>ActivePool</em> des trois branches sur Ethereum, le 7 septembre 2026. TVL, rendements et historique 12 mois : DeFiLlama. Audits et redéploiement : documentation et blog Liquity.</p>
  </td></tr>

  <!-- ============ 4. COURS ============ -->
  <tr><td style="padding:24px 36px 0 36px;">
    <table role="presentation" cellpadding="0" cellspacing="0"><tr>
      <td style="background-color:#eef0ff; border-radius:30px; padding:6px 16px; font-size:12px; font-weight:700; color:#4338ca; letter-spacing:1.2px;">📊 LES REPÈRES</td>
      <td style="padding-left:12px; font-size:12px; color:#94a3b8; white-space:nowrap;">au 10 septembre 2026</td>
    </tr></table>
  </td></tr>
  <tr><td style="padding:16px 36px 0 36px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #eef2f2; border-radius:12px; overflow:hidden;">
      <tr style="background-color:#1A2332;">
        <td style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8; letter-spacing:0.5px;">ACTIF</td>
        <td align="right" style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8; letter-spacing:0.5px;">PRIX</td>
        <td align="right" style="padding:11px 14px; font-size:12px; font-weight:600; color:#94a3b8; letter-spacing:0.5px;">7 J</td>
      </tr>
      <tr><td style="padding:13px 14px; font-size:16px; color:#1A2332;"><strong style="color:#dc2626;">BTC</strong> <span style="color:#94a3b8;">Bitcoin</span></td><td align="right" style="padding:13px 14px; font-size:16px; font-weight:700; color:#1A2332;">~77 268 $</td><td align="right" style="padding:13px 14px; font-size:15px; font-weight:700; color:#dc2626;">▼ −3,2 %</td></tr>
      <tr style="background-color:#f7fafa;"><td style="padding:13px 14px; font-size:16px; color:#1A2332;"><strong style="color:#dc2626;">ETH</strong> <span style="color:#94a3b8;">Ethereum</span></td><td align="right" style="padding:13px 14px; font-size:16px; font-weight:700; color:#1A2332;">~2 440 $</td><td align="right" style="padding:13px 14px; font-size:15px; font-weight:700; color:#dc2626;">▼ −0,8 %</td></tr>
      <tr><td style="padding:13px 14px; font-size:16px; color:#1A2332;"><strong style="color:#dc2626;">SOL</strong> <span style="color:#94a3b8;">Solana</span></td><td align="right" style="padding:13px 14px; font-size:16px; font-weight:700; color:#1A2332;">~100,2 $</td><td align="right" style="padding:13px 14px; font-size:15px; font-weight:700; color:#dc2626;">▼ −2,6 %</td></tr>
      <tr style="background-color:#f7fafa;"><td style="padding:13px 14px; font-size:16px; color:#1A2332;"><strong style="color:#dc2626;">HYPE</strong> <span style="color:#94a3b8;">Hyperliquid</span></td><td align="right" style="padding:13px 14px; font-size:16px; font-weight:700; color:#1A2332;">~81,1 $</td><td align="right" style="padding:13px 14px; font-size:15px; font-weight:700; color:#dc2626;">▼ −3,0 %</td></tr>
      <tr><td style="padding:13px 14px; font-size:16px; color:#1A2332;"><strong style="color:#dc2626;">BNB</strong> <span style="color:#94a3b8;"></span></td><td align="right" style="padding:13px 14px; font-size:16px; font-weight:700; color:#1A2332;">~710 $</td><td align="right" style="padding:13px 14px; font-size:15px; font-weight:700; color:#dc2626;">▼ −1,3 %</td></tr>
    </table>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4; border-left:4px solid #28B092; border-radius:8px; margin-top:14px;"><tr><td style="padding:14px 18px; font-size:16px; line-height:1.65; color:#1A2332;">💡 <strong>Notre avis :</strong> semaine rouge sur toute la ligne, et le repli s'est accéléré ces dernières heures : le bitcoin s'échange autour de <strong>77 300 $</strong>, après être monté jusqu'à <strong>81 000 $ le 4 septembre</strong> — soit près de <strong>5 % perdus</strong> depuis ce sommet.<br><br>Deux causes se cumulent : le pétrole repassé au-dessus de 100 $ sur fond d'escalade entre les États-Unis et l'Iran, et l'attente du chiffre de l'inflation américaine, publié demain. Quand le marché redoute une hausse des taux, il vend d'abord ce qui ne rapporte rien par soi-même.</td></tr></table>
    <p style="margin:8px 0 0 0; font-size:11px; line-height:1.5; color:#94a3b8;">Prix au 10 septembre 2026 ; variations sur 7 jours glissants (DeFiLlama).</p>
  </td></tr>

  <!-- DATA DE LA SEMAINE -->
  <tr><td style="padding:24px 36px 0 36px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#1A2332; background:linear-gradient(135deg,#1A2332,#2e1b8b); border-radius:14px;">
      <tr><td style="padding:22px 24px;">
        <div style="font-size:12px; font-weight:700; color:#F5A623; letter-spacing:1.2px; margin-bottom:8px;">💡 ÇA BRILLE</div>
        <div style="font-size:24px; font-weight:800; color:#ffffff; margin-bottom:10px; line-height:1.3;">480 M$ de frais en dix semaines</div>
        <div style="font-size:14px; line-height:1.7; color:#cbd5e1; margin-bottom:12px;">C'est ce que les utilisateurs de <strong style="color:#ffffff;">Robinhood Chain</strong> ont payé depuis le lancement de la chaîne, le 1er juillet. Et la trajectoire mérite un coup d'œil de près : <strong style="color:#ffffff;">le volume monte</strong> — 12,2 Md$ échangés sur les sept derniers jours, contre 8,9 Md$ la semaine précédente — <strong style="color:#ffffff;">pendant que les frais quotidiens redescendent</strong> : 13,0 M$ sur 24 h, contre un pic à 19,1 M$ le 2 septembre. Les dépôts, eux, progressent : 897 M$ immobilisés sur la chaîne, contre 820 M$ une semaine plus tôt.</div>
        <div style="font-size:14px; line-height:1.7; color:#cbd5e1; margin-bottom:12px;">Le carburant de tout ça, ce sont les memecoins lancés sur Pons — alors que la chaîne avait été bâtie pour tout autre chose. Robinhood est d'abord un <strong style="color:#ffffff;">courtier en Bourse</strong> : sa blockchain devait servir à faire circuler des <strong style="color:#ffffff;">actions tokenisées</strong>, son métier d'origine porté on-chain.</div>
        <div style="font-size:14px; line-height:1.7; color:#cbd5e1;">Un détail qui compte : <strong style="color:#ffffff;">Robinhood paie le gaz de ses utilisateurs depuis le lancement</strong>, une promotion de 90 jours qui s'arrête vers le <strong style="color:#ffffff;">29 septembre</strong>. L'extinction a d'ailleurs déjà commencé, le seuil de prise en charge étant passé de 5 $ à 0,50 $ par transaction à la mi-août.</div>
      </td></tr>
    </table>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0fdf4; border-left:4px solid #28B092; border-radius:8px; margin-top:14px;"><tr><td style="padding:14px 18px; font-size:16px; line-height:1.65; color:#1A2332;">💡 <strong>Notre avis :</strong> les chiffres sont spectaculaires, et on les regarde avec curiosité — mais nous, on évite les memecoins. La vraie question arrive fin septembre : que restera-t-il du volume et de la liquidité quand l'utilisateur paiera son gaz lui-même, et quand la mode sera passée ?<br><br>Peut-être que la chaîne reviendra alors à ce pour quoi elle avait été bâtie. Mais sur ce terrain-là, la place est déjà prise : <strong>Solana concentre plus de 96 % des échanges d'actions tokenisées</strong>, avec 4,9 Md$ traités sur le seul premier semestre 2026.<br><br>Robinhood a des atouts que personne d'autre n'a — des millions de clients déjà habitués à acheter des actions chez elle, et sa propre chaîne pour les accueillir. Reste que déloger un acteur installé est autrement plus difficile que d'attirer des lanceurs de memecoins avec du gaz offert. On regardera.</td></tr></table>
    <p style="margin:8px 0 0 0; font-size:11px; line-height:1.5; color:#94a3b8;">Frais, revenus, volume et TVL de Robinhood Chain relevés le 10 septembre 2026 (DeFiLlama). Part de marché des actions tokenisées : volumes du premier semestre 2026.</p>
  </td></tr>

  <tr><td style="padding:26px 36px 0 36px;"><div style="border-top:1px solid #eef2f2;"></div></td></tr>

  <!-- ============ DÉFINITIONS ============ -->
  <tr><td style="padding:24px 36px 0 36px;">
    <table role="presentation" cellpadding="0" cellspacing="0"><tr><td style="background-color:#fff4e0; border-radius:30px; padding:6px 16px; font-size:12px; font-weight:700; color:#b9770f; letter-spacing:1.2px;">📖 DÉFINITIONS</td></tr></table>
  </td></tr>
  <tr><td style="padding:16px 36px 0 36px; color:#1A2332;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        <td valign="top" width="20" style="font-size:16px; color:#F5A623; line-height:1.6;">•</td>
        <td style="font-size:16px; line-height:1.6;"><a href="https://www.cryptoluciole.com/glossaire/pool-de-stabilite" style="color:#28B092; font-weight:700; text-decoration:none;">Pool de stabilité</a> — la réserve dans laquelle un protocole puise pour absorber les liquidations. Tu y déposes un stablecoin ; le jour où un emprunteur passe sous son seuil, ton dépôt sert à solder sa dette et tu récupères son collatéral, avec une décote en ta faveur. C'est de là que vient le rendement — et c'est aussi le risque : tu peux te retrouver avec de l'ether au lieu de tes stablecoins, précisément le jour où le marché s'effondre.</td>
      </tr>
    </table>
  </td></tr>
  <tr><td style="padding:14px 36px 0 36px; color:#1A2332;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        <td valign="top" width="20" style="font-size:16px; color:#F5A623; line-height:1.6;">•</td>
        <td style="font-size:16px; line-height:1.6;"><a href="https://www.cryptoluciole.com/glossaire/cpi" style="color:#28B092; font-weight:700; text-decoration:none;">CPI <em>(Consumer Price Index)</em></a> — l'indice des prix à la consommation américain, la mesure officielle de l'inflation là-bas. Publié chaque mois, il conditionne les décisions de la banque centrale : une inflation qui remonte pousse à monter les taux, ce qui rend les actifs sans rendement — bitcoin compris — relativement moins attractifs.</td>
      </tr>
    </table>
  </td></tr>

  <!-- ============ PIED ============ -->
  <tr><td style="padding:28px 36px 0 36px;"><div style="border-top:1px solid #eef2f2;"></div></td></tr>
  <tr><td style="background-color:#1A2332; padding:24px 36px; margin-top:24px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>
      <td valign="middle" width="40"><img src="https://raw.githubusercontent.com/AntoineBatou/cryptoluciole/main/assets/logo/firefly-logo-white.png" width="32" alt="" style="display:block;width:32px;height:auto;"></td>
      <td valign="middle" style="padding-left:10px; font-size:14px; font-weight:700; color:#F5A623;">CryptoLuciole 🪲✨</td>
    </tr></table>
    <p style="margin:14px 0 0 0; font-size:11px; line-height:1.6; color:#94a3b8;">⚠️ Contenu purement pédagogique — <strong>pas un conseil en investissement</strong>. Fais tes propres recherches.</p>
    <p style="margin:12px 0 0 0; font-size:11px; line-height:1.6; color:#64748b;"><a href="%UNSUBSCRIBE_URL%" style="color:#94a3b8;">Se désabonner</a> &middot; CryptoLuciole</p>
  </td></tr>

</table>
</td></tr></table>
</body>
</html>`,
};
